kind: pipeline
name: default

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive --remote
  when:
    branch:
    - master

- name: build css
  image: node
  commands:
  - npm install -g sass postcss-cli autoprefixer
  - cd dev
  - make
  when:
    branch:
    - master

- name: build hugo
  image: plugins/hugo
  settings:
    hugo_version: 0.53
    validate: true
  when:
    branch:
    - master

- name: deploy ru version
  image: docker:git
  commands:
  - cd public/ru
  - git add --all
  - git commit --message "Update"
  - git push --force origin master
  when:
    branch:
    - master

- name: deploy en version
  image: docker:git
  commands:
  - cd public/en
  - git add --all
  - git commit --message "Update"
  - git push --force origin master
  when:
    branch:
    - master