kind: pipeline
name: default

steps:
- name: build css
  image: node
  commands:
  - npm install -g sass postcss-cli autoprefixer
  - cd dev
  - make

- name: build hugo
  image: plugins/hugo
  settings:
    hugo_version: 0.53
    validate: true

- name: deploy ru version
  image: alpine/git
  commands:
  - cd public/ru
  - git add --all
  - git commit --message "Update"
  - git push --force origin master

- name: deploy en version
  image: alpine/git
  commands:
  - cd public/en
  - git add --all
  - git commit --message "Update"
  - git push --force origin master