kind: pipeline
name: default

steps:
- name: submodules
  image: alpine/git
  environment:
    SSH_KEY:
      from_secret: github_ssh_key
    GIT_NAME:
      from_secret: name
    GIT_EMAIL:
      from_secret: email
  commands:
  # write the ssh key to disk
  - mkdir /root/.ssh
  - echo -n "$SSH_KEY" > /root/.ssh/id_rsa
  - chmod 600 /root/.ssh/id_rsa
  # add github to known hosts
  - touch /root/.ssh/known_hosts
  - chmod 600 /root/.ssh/known_hosts
  - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null
  # git config
  - git config user.email "${GIT_EMAIL}"
  - git config user.name "${GIT_NAME}"
  # pull the git submodules
  - git submodule update --init
  - git submodule update --init --recursive
  when:
    branch:
    - master

- name: build css
  image: node
  commands:
  - npm install -g sass postcss-cli autoprefixer
  - cd dev
  - make
  when:
    branch:
    - master

- name: build hugo
  image: plugins/hugo
  settings:
    hugo_version: 0.53
    validate: true
  when:
    branch:
    - master

- name: publish ru version
  image: alpine/git
  commands:
  - cd public/ru
  - git add --all
  - git commit --message "Update"
  - git push --force origin master
  when:
    branch:
    - master

- name: publish en version
  image: alpine/git
  commands:
  - cd public/en
  - git add --all
  - git commit --message "Update"
  - git push --force origin master
  when:
    branch:
    - master