kind: pipeline
name: default

steps:
- name: pull sites
  image: alpine/git
  commands:
  - mkdir public
  - cd public
  - git clone https://github.com/agladky/agladky.github.io.git ru
  - git clone https://github.com/agladky/agladky.com.git en

- name: build css
  image: node
  commands:
  - npm install -g sass postcss-cli autoprefixer
  - cd dev
  - make

- name: load book reviews
  image: python:3.7-alpine3.9
  environment:
    GOODREADS_KEY:
      from_secret: goodreads_key
  commands:
  - cd dev
  - python --version
  - python goodreads_reviews.py --key $GOODREADS_KEY
  - mv book-reviews.json ../data 

- name: build hugo
  image: plugins/hugo
  settings:
    hugo_version: 0.53
    validate: true

- name: publish sites
  image: alpine/git
  environment:
    SSH_KEY:
      from_secret: github_ssh_key
    GIT_NAME:
      from_secret: name
    GIT_EMAIL:
      from_secret: email
  commands:
  # write the ssh key to disk
  - mkdir /root/.ssh
  - echo -n "$SSH_KEY" > /root/.ssh/id_rsa
  - chmod 600 /root/.ssh/id_rsa
  # add github to known hosts
  - touch /root/.ssh/known_hosts
  - chmod 600 /root/.ssh/known_hosts
  - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null
  # fill config
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "$GIT_NAME"
  # commit ru version
  - cd public/ru
  - git remote set-url origin git@github.com:agladky/agladky.github.io.git
  - git add --all
  - git commit --message "Update"
  - git push --force origin master
  - cd ../..
  # commit en version
  - cd public/en
  - git remote set-url origin git@github.com:agladky/agladky.com.git
  - git add --all
  - git commit --message "Update"
  - git push --force origin master
  - cd ../..

trigger:
  branch:
  - master
