kind: pipeline
name: default

steps:
- name: build css
  image: node
  commands:
  - npm install -g sass postcss-cli autoprefixer
  - cd dev
  - make

- name: build hugo
  image: plugins/hugo
  settings:
    hugo_version: 0.53
