kind: pipeline
name: default

steps:
- name: build css
  image: node
  commands:
  - npm install -g sass
  - npm install -g postcss-cli
  - cd dev
  - make

- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.54
    pull: always
    validate: true