baseurl = "https://agladky.ru/"
languageCode = "ru-RU"
defaultContentLanguage = "ru"
buildDrafts = false
canonifyUrls = true  # Enable to turn relative URLs into absolute.
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
googleAnalytics = "UA-75808442-1"
disqusShortname = "agladky"
pluralizeListTitles = false
pygmentsUseClasses = true
pygmentsCodeFences = true
paginate = 10

[languages]
  [languages.ru]
    title = "Блог Анатолия Гладкого"
    [languages.ru.author]
      name = "Анатолий Гладкий"
    [languages.ru.params]
      description = "Блог Анатолия Гладкого"
  [languages.en]
    title = "Anatoly Gladky Blog"
    [languages.en.author]
      name = "Anatoly Gladky"
    [languages.en.params]
      description = "Anatoly Gladky Blog"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  fixed = ":title/"
  blog = "blog/:filename/"

[Params]
  isMainMenuEnabled = false

  # Реализовать
  # Сравнивать страницы и заимствовать код, если надо
  # Перевести css на bem
  # i18n_flags = false  # whether to display small country flags for available translations
  # latestpostscount = 5

[[menu.main]]
  name = "Блог"
  pre = "<i class='fa fa-heart'></i>"
  weight = -110
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "Контакты"
  pre = "<i class='fa fa-road'></i>"
  weight = -100
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "Код"
  pre = "<i class='fa fa-road'></i>"
  weight = -90
  identifier = "code"
  url = "/code/"
