languageCode = "ru-RU"
defaultContentLanguage = "ru"
buildDrafts = false
canonifyUrls = true  # Enable to turn relative URLs into absolute.
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
staticDir = "statics/base"
googleAnalytics = "UA-75808442-1"
disqusShortname = "agladky"
pluralizeListTitles = false
pygmentsUseClasses = true
pygmentsCodeFences = true
paginate = 10

[languages]
  [languages.ru]
    baseurl = "https://agladky.ru/"
    title = "Анатолий Гладкий"
    weight = 1
    staticDir2 = "statics/ru"
    [languages.ru.author]
      name = "Анатолий Гладкий"
    [languages.ru.params]
      description = "Блог Анатолия Гладкого"
    [[languages.ru.menu.main]]
      identifier = "blog"
      name = "Блог"
      weight = 10
      url = "/blog/"
    [[languages.ru.menu.main]]
      identifier = "books"
      name = "Обзоры книг"
      weight = 20
      url = "/books/"
    [[languages.ru.menu.main]]
      identifier = "search"
      name = "Поиск"
      weight = 30
      url = "https://www.google.ru/search?q=site%3Aagladky.ru"
  [languages.en]
    baseurl = "https://agladky.com/"
    title = "Anatoly Gladky"
    weight = 2
    staticDir2 = "statics/en"
    [languages.en.author]
      name = "Anatoly Gladky"
    [languages.en.params]
      description = "Anatoly Gladky Blog"
    [[languages.en.menu.main]]
      identifier = "books"
      name = "Book Reviews"
      weight = 20
      url = "/books/"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  fixed = ":title/"
  blog = "blog/:slug/"
