baseurl = "http://www.agladky.ru/"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "ru-RU"
layoutdir = "layouts"
publishdir = "public"
author = "Анатолий Гладкий"
title = "Блог Анатолия Гладкого"
googleAnalytics = "UA-75808442-1"
pluralizelisttitles = false
pygmentsuseclasses = true
PygmentsCodeFences = true
paginate = 10
SectionPagesMenu = "main"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  fixed = ":title/"
  blog = "blog/:slug/" # тут надо не slug а имя файла

[Params]
  Author = "Анатолий Гладкий"
  disqusShortname = "agladky"
  CacheBuster = true
  DateForm = "Jan 2, 2006"
  DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
  Description = "Блог Анатолия Гладкого"
  FaviconFile = "img/leaf.ico"
  GATracker = "UA-75808442-1"
  Lang = "ru"
  IsMainMenuEnabled = false
  # ExtraCssFiles = [ "/css/override.css" ] # relative to public directory

[[menu.main]]
  name = "Блог"
  pre = "<i class='fa fa-heart'></i>"
  weight = -110
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "Контакты"
  pre = "<i class='fa fa-road'></i>"
  weight = -100
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "Код"
  pre = "<i class='fa fa-road'></i>"
  weight = -90
  identifier = "code"
  url = "/code/"
