baseurl = "https://agladky.ru/"
languageCode = "ru-RU"
defaultContentLanguage = "ru"
buildDrafts = false
canonifyUrls = true  # Enable to turn relative URLs into absolute.
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
googleAnalytics = "UA-75808442-1"
disqusShortname = "agladky"
pluralizeListTitles = false
pygmentsUseClasses = true
pygmentsCodeFences = true
paginate = 10

[languages]
  [languages.ru]
    title = "Анатолий Гладкий"
    [languages.ru.author]
      name = "Анатолий Гладкий"
    [languages.ru.params]
      description = "Блог Анатолия Гладкого" # Дописать описание о себе !!!
    [[languages.ru.menu.main]]
      identifier = "blog"
      name = "Блог"
      weight = 10
      url = "/blog/"
  [languages.en]
    title = "Anatoly Gladky"
    [languages.en.author]
      name = "Anatoly Gladky"
    [languages.en.params]
      description = "Anatoly Gladky Blog"
    [[languages.en.menu.main]]
      identifier = "blog"
      name = "Blog"
      weight = 10
      url = "/blog/"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  fixed = ":title/"
  blog = "blog/:slug/"
