baseurl = "https://agladky.ru/"
languageCode = "ru-RU"
defaultContentLanguage = "ru"
buildDrafts = false
canonifyUrls = true  # Enable to turn relative URLs into absolute.
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
googleAnalytics = "UA-75808442-1"
disqusShortname = "agladky"
pluralizeListTitles = false
pygmentsUseClasses = true
pygmentsCodeFences = true
paginate = 10

[languages]
  [languages.ru]
    title = "Анатолий Гладкий"
    [languages.ru.author]
      name = "Анатолий Гладкий"
    [languages.ru.params]
      description = "Блог Анатолия Гладкого" # Дописать описание о себе !!!
    [[languages.ru.menu.main]]
      identifier = "blog"
      name = "Блог"
      weight = 10
      url = "/blog/"
    [[languages.ru.menu.main]]
      identifier = "books"
      name = "Книги"
      weight = 20
      url = "/books/"
  [languages.en]
    title = "Anatoly Gladky"
    [languages.en.author]
      name = "Anatoly Gladky"
    [languages.en.params]
      description = "Anatoly Gladky Blog"
    [[languages.en.menu.main]]
      identifier = "blog"
      name = "Blog"
      weight = 10
      url = "/blog/"
    [[languages.en.menu.main]]
      identifier = "books"
      name = "Books"
      weight = 20
      url = "/books/"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  fixed = ":title/"
  blog = "blog/:filename/"

# Заголовок блога — Blog, это неправильно
# Перевести css на bem
# i18n_flags = false  # whether to display small country flags for available translations
# latestpostscount = 5
# Проверить отображение постов в твитере