name: CD

on:
  push:
    branches: 
      - master
  schedule:
    - cron:  '0 0 */3 * *'
  

jobs:
  update-sites:
    name: Update ru and en personal sites
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout raw sites
      uses: actions/checkout@v2

    - name: Checkout ru site
      uses: actions/checkout@v2
      with:
        repository: agladky/agladky.github.io
        path: public/ru

    - name: Checkout en site
      uses: actions/checkout@v2
      with:
        repository: agladky/agladky.com
        path: public/en

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    
    - name: Load book reviews
      env:
       GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
      run: |
        python --version
        python dev/goodreads_reviews.py --key "$GOODREADS_KEY" --path content/books

    - name: Echo something
      run: |
        echo "$(pwd)"
