name: CD

on:
  push:
    branches: 
      - master
  schedule:
    - cron:  '0 0 */3 * *'
  

jobs:
  update-sites:
    name: Update ru and en personal sites
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: echo workspace
      run: |
        echo "${{ github.workspace }}"

    # - name: load book reviews
      # image: python:3.7-alpine3.9
      # env:
      #  GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
      # run: |
      #   python --version
      #   python dev/goodreads_reviews.py --key "$GOODREADS_KEY" --path content/books